---
version: "3.5"

services:
  notebook:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: notebook
    volumes:
      - "./work:/home/jovyan/work"
      - "./data:/home/jovyan/data"
    ports:
      - "8888:8888"
    environment:
      - GRANT_SUDO="yes"
    user:
      "root"
    command: ["/bin/sh", "-c", "jupyter notebook --allow-root"]