---
version: "3.5"

services:
  notebook:
    image: jupyter/pyspark-notebook
    container_name: notebook
    volumes:
      - "./work:/home/jovyan/work"
      - "./data:/home/jovyan/data"
      - "./misc:/home/jovyan/misc"
    ports:
      - "8888:8888"
    environment:
      - GRANT_SUDO="yes"
    user:
      "root"